
var CONFIG = {
  MILESTONE: '4.0.0',
  SPREADSHEET_ID_KEY: '1f6vzPD6VztFVdH-i5Yq-5ZUuBp_6VsU4w-h1_QXUr08',
  SCHOOL_NAME_KEY: 'SCHOOL_NAME',
  DEFAULT_SCHOOL_NAME: 'بوابة المناهج والتدريس',
  ACTIVE_LESSON_TEMPLATE_ID_KEY: 'ACTIVE_LESSON_TEMPLATE_ID',
  ACTIVE_LESSON_TEMPLATE_VERSION_KEY: 'ACTIVE_LESSON_TEMPLATE_VERSION'
};
