
var CONFIG = {
  MILESTONE: '4.0.0',
  SPREADSHEET_ID_KEY: 'SPREADSHEET_ID',
  SCHOOL_NAME_KEY: 'SCHOOL_NAME',
  DEFAULT_SCHOOL_NAME: 'بوابة المناهج والتدريس',
  ACTIVE_LESSON_TEMPLATE_ID_KEY: 'ACTIVE_LESSON_TEMPLATE_ID',
  ACTIVE_LESSON_TEMPLATE_VERSION_KEY: 'ACTIVE_LESSON_TEMPLATE_VERSION'
};
