
var SHEETS = ['CONFIG','SEQUENCES','USERS','ROLES','ROLE_PERMISSIONS','USER_ASSIGNMENTS','ACADEMIC_YEARS','GRADES','CLASSES','STUDENTS','TEACHERS','SUBJECTS','CURRICULUM_UNITS','LESSONS','LESSON_CONTENT','LESSON_WORKFLOW','EVALUATION_FORMS','EVALUATION_CRITERIA','EVALUATIONS','EVALUATION_RESPONSES','REPORTS','FILES','AUDIT_LOG','SYSTEM_LOG','BACKUP_JOBS','ARCHIVE_INDEX'];
var ID_PREFIXES = {student:'STD',teacher:'TCH',lesson:'LES',evaluation:'EVA',report:'RPT',academicYear:'ACY',grade:'GRD',class:'CLS',subject:'SUB',curriculumUnit:'UNT',lessonContent:'LCT',lessonWorkflow:'LWF',file:'FIL'};
var LESSON_STATUSES = {DRAFT:'مسودة',SUBMITTED:'مرسلة للمراجعة',UNDER_REVIEW:'قيد المراجعة',REVISION_REQUIRED:'تحتاج إلى تعديل',APPROVED:'معتمدة',PUBLISHED:'منشورة',ARCHIVED:'مؤرشفة'};
var LESSON_STATUS_TRANSITIONS = {DRAFT:['SUBMITTED'],SUBMITTED:['UNDER_REVIEW'],UNDER_REVIEW:['APPROVED','REVISION_REQUIRED'],REVISION_REQUIRED:['SUBMITTED'],APPROVED:['PUBLISHED'],PUBLISHED:['ARCHIVED'],ARCHIVED:[]};
var LESSON_ACTION_PERMISSIONS = {CREATE:'MANAGE_LESSONS',DRAFT_SAVE:'MANAGE_LESSONS',SUBMIT:'REVIEW_LESSONS',REVIEW_START:'REVIEW_LESSONS',REVIEW_COMMENT:'REVIEW_LESSONS',APPROVE:'APPROVE_LESSONS',PUBLISH:'PUBLISH_LESSONS',ARCHIVE:'ARCHIVE_LESSONS',GENERATE_DOCUMENT:'GENERATE_LESSON_DOCS',GENERATE_PDF:'GENERATE_LESSON_DOCS'};
var LESSON_FILE_TYPES = {DOCUMENT:'DOCUMENT',PDF:'PDF'};
var EVALUATION_STATUSES = {NOT_STARTED:'لم تبدأ',IN_PROGRESS:'قيد التنفيذ',SUBMITTED:'مرسلة',LOCKED:'مغلقة',ARCHIVED:'مؤرشفة'};
var EVALUATION_FORM_STATUSES = {DRAFT:'مسودة',ACTIVE:'نشطة',ARCHIVED:'مؤرشفة'};
var REPORT_FILE_TYPES = {DOCUMENT:'DOCUMENT',PDF:'PDF'};
var REPORT_STATUSES = {ACTIVE:'نشط',SUPERSEDED:'مستبدل بنسخة أحدث',ARCHIVED:'مؤرشف'};
var REPORT_TERMS = {FULL_YEAR:'العام الدراسي كاملاً',FIRST:'الفصل الأول',SECOND:'الفصل الثاني',THIRD:'الفصل الثالث',CUSTOM:'فترة مخصصة'};
var REPORT_INCLUDED_EVALUATION_STATUSES = ['SUBMITTED','LOCKED'];
var ROLES = {ADMIN:'مدير النظام',CURRICULUM:'مسؤول المناهج والتنسيق',CONTENT:'فريق إعداد المحتوى',EVALUATION:'فريق التصميم والتقييم',TEACHER:'المعلم',SUPERVISOR:'المشرف / المنسق',MANAGEMENT:'الإدارة'};
var DRIVE_FOLDERS = ['01 خطط الدروس','02 PDF الدروس','03 تقارير الطلاب','04 ملفات التقييم','05 القوالب','06 النسخ الاحتياطية','07 الأرشيف','08 ملفات النظام'];
