
function diagnostics_(){var ss=DatabaseService.spreadsheet();return {spreadsheet:ss.getId(),sheets:SHEETS.filter(function(n){return !!ss.getSheetByName(n);}),milestone:CONFIG.MILESTONE,lessonStatuses:LESSON_STATUSES,lessonTransitions:LESSON_STATUS_TRANSITIONS};}
function runDiagnostics(){return envelope_(true,diagnostics_(),'تم تشغيل الفحص');}
function runLessonDiagnostics(){var summary={milestone:CONFIG.MILESTONE,validDraftTransition:lessonTransitionAllowed_('DRAFT','SUBMITTED'),validReviewTransition:lessonTransitionAllowed_('UNDER_REVIEW','APPROVED'),validRevisionTransition:lessonTransitionAllowed_('REVISION_REQUIRED','SUBMITTED'),invalidTransition:lessonTransitionAllowed_('DRAFT','APPROVED')};return envelope_(true,summary,'تم تشغيل تشخيص سير الدروس');}
// Milestone 5: static self-check for the teacher workspace visibility rule,
// exercised against sample rows so it never touches Sheets/Session/Drive.
function runWorkspaceVisibilityDiagnostics_(){var sample=[{id:'L1',teacherEmail:'teacher@a.com',status:'DRAFT'},{id:'L2',teacherEmail:'other@a.com',status:'DRAFT'},{id:'L3',teacherEmail:'other@a.com',status:'PUBLISHED'}];var teacherView=filterLessonsByVisibility_(sample,{elevated:false,email:'teacher@a.com'});var elevatedView=filterLessonsByVisibility_(sample,{elevated:true,email:'teacher@a.com'});var summary={teacherSeesOwnDraft:teacherView.some(function(r){return r.id==='L1';}),teacherHidesOthersDraft:!teacherView.some(function(r){return r.id==='L2';}),teacherSeesOthersPublished:teacherView.some(function(r){return r.id==='L3';}),elevatedSeesEverything:elevatedView.length===sample.length};return envelope_(true,summary,'تم تشغيل تشخيص مساحة عمل المعلم');}
// Milestone 7: static self-check for report inclusion/summary rules, exercised
// against sample rows so it never touches Sheets/Session/Drive/Docs.
function runReportDiagnostics(){var scopeAll={all:true,classes:[],subjects:[]};var scopeTeacher={all:false,classes:['C1'],subjects:['S1']};var inScopeEvaluation={studentId:'ST1',classId:'C1',subjectId:'S1',status:'SUBMITTED'};var outOfScopeEvaluation={studentId:'ST1',classId:'C2',subjectId:'S1',status:'SUBMITTED'};var entries=[{evaluationId:'E1',formId:'F1',formVersion:1,formTitle:'نموذج',responses:[{criterionId:'CR1',label:'الانضباط',responseType:'RATING',value:'4'},{criterionId:'CR1',label:'الانضباط',responseType:'RATING',value:'2'}]}];var summary=computeReportSummary_(entries);var summaryOk=summary.evaluationsIncluded===1&&summary.criteria.length===1&&summary.criteria[0].average===3;var termsValid=!!REPORT_TERMS.FULL_YEAR&&!!REPORT_TERMS.CUSTOM;var result={teacherIncludesOwnScope:evaluationInScope_(inScopeEvaluation,scopeTeacher),teacherExcludesOtherScope:!evaluationInScope_(outOfScopeEvaluation,scopeTeacher),adminIncludesEverything:evaluationInScope_(outOfScopeEvaluation,scopeAll),summaryAverageCorrect:summaryOk,reportTermsConfigured:termsValid};return envelope_(true,result,'تم تشغيل تشخيص محرك التقارير');}
