// Milestone 4 assessment:
// This repo uses a flat Apps Script architecture where reusable services are defined per concern
// (DatabaseService, DriveService, DocumentService, AuthFoundationService, UserRoleService, AuditService,
// and SystemLogService) and the domain tables already include LESSONS, LESSON_CONTENT, LESSON_WORKFLOW,
// and FILES. That means the correct change is to add a centralized LessonWorkflowService rather than
// scattering workflow logic across controllers and page handlers. The service must preserve history in
// LESSON_WORKFLOW and FILES, validate save-vs-submit states server-side, and block invalid transitions
// while keeping DB writes append-only/no-destructive.

function lessonTransitionAllowed_(fromStatus, toStatus){var from=String(fromStatus||'');var to=String(toStatus||'');var valid=LESSON_STATUS_TRANSITIONS[from]||[];return valid.indexOf(to)>=0;}

function ensureLessonSchema_(){DatabaseService.ensureSheet('LESSONS',['id','title','lessonCode','status','teacherEmail','subject','grade','unitId','summary','contentJson','version','approvedVersion','publishedVersion','documentFileId','pdfFileId','reviewHistory','createdAt','updatedAt']);DatabaseService.ensureSheet('LESSON_CONTENT',['id','lessonId','section','content','version','createdAt','updatedAt']);DatabaseService.ensureSheet('LESSON_WORKFLOW',['id','lessonId','fromStatus','toStatus','action','actorEmail','comment','metadata','timestamp']);DatabaseService.ensureSheet('FILES',['id','entityType','entityId','type','fileName','driveFileId','folderPath','mimeType','templateId','templateVersion','version','metadata','status','createdAt','updatedAt']);}

function getLessonStatusLabel_(status){return LESSON_STATUSES[String(status||'')]||String(status||'');}

function getActiveLessonTemplate_(){var cfg=DatabaseService.rows('CONFIG')||[];var match=cfg.filter(function(r){return r.key===CONFIG.ACTIVE_LESSON_TEMPLATE_ID_KEY;})[0];if(match&&safeText_(match.value))return match.value;return safeText_(PropertiesService.getScriptProperties().getProperty(CONFIG.ACTIVE_LESSON_TEMPLATE_ID_KEY));}

function getActiveLessonTemplateVersion_(){var cfg=DatabaseService.rows('CONFIG')||[];var match=cfg.filter(function(r){return r.key===CONFIG.ACTIVE_LESSON_TEMPLATE_VERSION_KEY;})[0];if(match&&safeText_(match.value))return match.value;return safeText_(PropertiesService.getScriptProperties().getProperty(CONFIG.ACTIVE_LESSON_TEMPLATE_VERSION_KEY))||'1.0';}

function getLessonById_(lessonId){ensureLessonSchema_();return DatabaseService.find('LESSONS',lessonId);} 

function lessonReviewHistory_(lesson){var reviewHistory = lesson && lesson.reviewHistory ? lesson.reviewHistory : [];if(typeof reviewHistory === 'string'){try{return JSON.parse(reviewHistory);}catch(e){return [];}}return Array.isArray(reviewHistory)?reviewHistory:[];}

function writeLessonHistory_(lessonId, entry){var lesson=getLessonById_(lessonId);if(!lesson)return null;var history=lessonReviewHistory_(lesson);history.push(entry);lesson.reviewHistory=json_(history);DatabaseService.upsert('LESSONS',lesson);return history;}

function recordLessonWorkflow_(lessonId, fromStatus, toStatus, action, comment, metadata){ensureLessonSchema_();var row={id:uuid_(),lessonId:String(lessonId),fromStatus:String(fromStatus||''),toStatus:String(toStatus||''),action:String(action||'TRANSITION'),actorEmail:currentEmail_(),comment:safeText_(comment||''),metadata:json_(metadata||{}),timestamp:now_()};DatabaseService.append('LESSON_WORKFLOW',row);return row;}

function validateLessonDraft_(data){data=data||{};var required=['title','subject','grade'];required.forEach(function(k){if(!safeText_(data[k]))throw Error('الحقل المطلوب مفقود: '+k);});return data;}

function validateLessonSubmission_(lesson){if(!lesson)throw Error('الدروس غير موجود');if(!safeText_(lesson.title))throw Error('عنوان الدرس مطلوب');if(!safeText_(lesson.subject))throw Error('مادة الدرس مطلوبة');if(!safeText_(lesson.grade))throw Error('المرحلة أو الصف مطلوبة');if(!safeText_(lesson.summary)&&!safeText_(lesson.contentJson))throw Error('لا يمكن إرسال درس فارغ بدون محتوى أو ملخص');return lesson;}

function registerLessonFile_(entityId, type, fileName, driveFileId, folderPath, templateId, templateVersion, version, metadata){ensureLessonSchema_();var fileRecord={id:uuid_(),entityType:'LESSON',entityId:String(entityId),type:String(type||'').toUpperCase(),fileName:safeText_(fileName)||('lesson-'+String(entityId)),driveFileId:safeText_(driveFileId)||'',folderPath:safeText_(folderPath)||'',mimeType:'application/octet-stream',templateId:safeText_(templateId||''),templateVersion:safeText_(templateVersion||''),version:Number(version||1),metadata:json_(metadata||{}),status:'ACTIVE',createdAt:now_(),updatedAt:now_()};DatabaseService.append('FILES',fileRecord);return fileRecord;}

function findLessonFileRecord_(lessonId, type){var rows=DatabaseService.rows('FILES')||[];return rows.filter(function(r){return String(r.entityType)==='LESSON'&&String(r.entityId)===String(lessonId)&&String(r.type||'').toUpperCase()===String(type||'').toUpperCase();}).sort(function(a,b){return Number(b.version||0)-Number(a.version||0);})[0]||null;}

function getLessonFolderPath_(target){var folders=DriveService.folders();return folders[target]||DriveService.root();}

function transitionLesson_(lessonId, toStatus, metadata){ensureLessonSchema_();var lesson=getLessonById_(lessonId);if(!lesson)throw Error('الدروس غير موجود');var fromStatus=String(lesson.status||'DRAFT');var valid=LESSON_STATUS_TRANSITIONS[fromStatus]||[];if(valid.indexOf(toStatus)<0){throw Error('انتقال الحالة غير مسموح: '+fromStatus+' -> '+toStatus);}var before=json_(lesson);lesson.status=String(toStatus);lesson.updatedAt=now_();if(toStatus==='APPROVED'&&(!lesson.approvedVersion||Number(lesson.approvedVersion)<Number(lesson.version||1)))lesson.approvedVersion=Number(lesson.version||1);if(toStatus==='PUBLISHED'&&(!lesson.publishedVersion||Number(lesson.publishedVersion)<Number(lesson.version||1)))lesson.publishedVersion=Number(lesson.version||1);DatabaseService.upsert('LESSONS',lesson);recordLessonWorkflow_(lessonId,fromStatus,toStatus,metadata&&metadata.action||'TRANSITION',metadata&&metadata.comment||'',metadata||{});audit_('STATUS_CHANGE','LESSONS',lessonId,JSON.parse(before),lesson);return lesson;}

function createLesson_(data){authorize_('MANAGE_LESSONS');ensureLessonSchema_();var payload=data||{};var clean=validateLessonDraft_(payload);var lessonId=String(payload.id||nextId_('lesson'));var lesson={id:lessonId,title:safeText_(clean.title),lessonCode:safeText_(clean.lessonCode)||lessonId,teacherEmail:safeText_(clean.teacherEmail||currentEmail_()),status:'DRAFT',subject:safeText_(clean.subject),grade:safeText_(clean.grade),unitId:safeText_(clean.unitId||''),summary:safeText_(clean.summary||''),contentJson:typeof clean.contentJson==='string'?clean.contentJson:json_(clean.content||{}),version:Number(clean.version||1),approvedVersion:'',publishedVersion:'',documentFileId:'',pdfFileId:'',reviewHistory:json_([]),createdAt:now_(),updatedAt:now_()};DatabaseService.append('LESSONS',lesson);audit_('CREATE','LESSONS',lesson.id,null,lesson);return lesson;}

function getLesson_(lessonId){authorize_('VIEW_LESSONS');var lesson=getLessonById_(lessonId);if(!lesson)throw Error('الدروس غير موجود');return lesson;}

function saveLessonDraft_(lessonId,data){authorize_('MANAGE_LESSONS');var lesson=getLessonById_(lessonId);if(!lesson)throw Error('الدروس غير موجود');if(String(lesson.status)==='PUBLISHED'||String(lesson.status)==='ARCHIVED')throw Error('لا يمكن تعديل درس منشور أو مؤرشف');var payload=data||{};var clean=validateLessonDraft_(payload);var before=json_(lesson);lesson.title=safeText_(clean.title || lesson.title);lesson.subject=safeText_(clean.subject || lesson.subject);lesson.grade=safeText_(clean.grade || lesson.grade);lesson.unitId=safeText_(clean.unitId || lesson.unitId || '');lesson.summary=safeText_(clean.summary || lesson.summary || '');lesson.teacherEmail=safeText_(clean.teacherEmail || lesson.teacherEmail || currentEmail_());lesson.contentJson=typeof clean.contentJson==='string'?clean.contentJson:json_(clean.content || JSON.parse(lesson.contentJson||'{}'));lesson.updatedAt=now_();lesson.version=Number(lesson.version||1);DatabaseService.upsert('LESSONS',lesson);audit_('DRAFT_SAVE','LESSONS',lessonId,JSON.parse(before),lesson);return lesson;}

function submitLessonForReview_(lessonId, comment){authorize_('REVIEW_LESSONS');var lesson=getLessonById_(lessonId);if(!lesson)throw Error('الدروس غير موجود');validateLessonSubmission_(lesson);var nextStatus='SUBMITTED';if(!lessonTransitionAllowed_(String(lesson.status||'DRAFT'),nextStatus))throw Error('لا يمكن إرسال درس في حالة '+getLessonStatusLabel_(lesson.status));var next=transitionLesson_(lessonId,nextStatus,{action:'SUBMIT_FOR_REVIEW',comment:comment||''});writeLessonHistory_(lessonId,{action:'SUBMIT_FOR_REVIEW',comment:comment||'',status:nextStatus,timestamp:now_()});return next;}

function requestRevision_(lessonId, comment){authorize_('REVIEW_LESSONS');var lesson=getLessonById_(lessonId);if(!lesson)throw Error('الدروس غير موجود');if(!lessonTransitionAllowed_(String(lesson.status||'DRAFT'),'REVISION_REQUIRED'))throw Error('لا يمكن طلب تعديل في الحالة الحالية');var next=transitionLesson_(lessonId,'REVISION_REQUIRED',{action:'REQUEST_REVISION',comment:comment||''});writeLessonHistory_(lessonId,{action:'REQUEST_REVISION',comment:comment||'',status:'REVISION_REQUIRED',timestamp:now_()});return next;}

function approveLesson_(lessonId, comment){authorize_('APPROVE_LESSONS');var lesson=getLessonById_(lessonId);if(!lesson)throw Error('الدروس غير موجود');if(!lessonTransitionAllowed_(String(lesson.status||'DRAFT'),'APPROVED'))throw Error('لا يمكن اعتماد درس في الحالة الحالية');var next=transitionLesson_(lessonId,'APPROVED',{action:'APPROVE',comment:comment||''});writeLessonHistory_(lessonId,{action:'APPROVE',comment:comment||'',status:'APPROVED',timestamp:now_()});return next;}

function publishLesson_(lessonId, comment){authorize_('PUBLISH_LESSONS');var lesson=getLessonById_(lessonId);if(!lesson)throw Error('الدروس غير موجود');if(!lessonTransitionAllowed_(String(lesson.status||'DRAFT'),'PUBLISHED'))throw Error('لا يمكن نشر درس في الحالة الحالية');var next=transitionLesson_(lessonId,'PUBLISHED',{action:'PUBLISH',comment:comment||''});writeLessonHistory_(lessonId,{action:'PUBLISH',comment:comment||'',status:'PUBLISHED',timestamp:now_()});return next;}

function archiveLesson_(lessonId, comment){authorize_('ARCHIVE_LESSONS');var lesson=getLessonById_(lessonId);if(!lesson)throw Error('الدروس غير موجود');if(!lessonTransitionAllowed_(String(lesson.status||'DRAFT'),'ARCHIVED'))throw Error('لا يمكن أرشفة درس في الحالة الحالية');var next=transitionLesson_(lessonId,'ARCHIVED',{action:'ARCHIVE',comment:comment||''});writeLessonHistory_(lessonId,{action:'ARCHIVE',comment:comment||'',status:'ARCHIVED',timestamp:now_()});return next;}

function buildLessonDocumentContent_(lesson){var body = typeof lesson.contentJson === 'string' ? JSON.parse(lesson.contentJson) : (lesson.content || {});var sections=[];var contentSections = body.sections || [body];contentSections.forEach(function(section){var title = section.title || 'محتوى';var text = section.body || section.content || '';sections.push(title + '\n\n' + text);});return 'عنوان الدرس: ' + (lesson.title||'') + '\n\n' + 'المادة: ' + (lesson.subject||'') + '\n\n' + 'المرحلة: ' + (lesson.grade||'') + '\n\n' + 'الملخص: ' + (lesson.summary||'') + '\n\n' + sections.join('\n\n');}

function generateLessonDocument_(lessonId, templateId){authorize_('GENERATE_LESSON_DOCS');var lesson=getLessonById_(lessonId);if(!lesson)throw Error('الدروس غير موجود');if(String(lesson.status)!=='APPROVED'&&String(lesson.status)!=='PUBLISHED')throw Error('يجب اعتماد الدرس قبل توليد الوثيقة');var existing=findLessonFileRecord_(lessonId,LESSON_FILE_TYPES.DOCUMENT);if(existing&&safeText_(existing.driveFileId)){return existing;}var activeTemplate = safeText_(templateId || getActiveLessonTemplate_());if(!activeTemplate)throw Error('لا توجد قالب درس نشط');var folder=getLessonFolderPath_('01 خطط الدروس');var doc=DocumentApp.create((lesson.lessonCode||lessonId)+' - '+(lesson.title||'درس'));var file=DriveApp.getFileById(doc.getId());if(folder && folder.addFile){folder.addFile(file);}var templateVersion=getActiveLessonTemplateVersion_();var fileRecord=registerLessonFile_(lessonId,LESSON_FILE_TYPES.DOCUMENT,(lesson.lessonCode||lessonId)+' - '+(lesson.title||'درس'),file.getId(),folder.getName?folder.getName():('01 خطط الدروس'),activeTemplate,templateVersion,lesson.version||1,{templateId:activeTemplate,templateVersion:templateVersion,generatedBy:currentEmail_(),generatedAt:now_()});lesson.documentFileId=fileRecord.id;lesson.updatedAt=now_();DatabaseService.upsert('LESSONS',lesson);return fileRecord;}

function generateLessonPdf_(lessonId){authorize_('GENERATE_LESSON_DOCS');var lesson=getLessonById_(lessonId);if(!lesson)throw Error('الدروس غير موجود');if(String(lesson.status)!=='APPROVED'&&String(lesson.status)!=='PUBLISHED')throw Error('يجب اعتماد الدرس قبل توليد ملف PDF');var existing=findLessonFileRecord_(lessonId,LESSON_FILE_TYPES.PDF);if(existing&&safeText_(existing.driveFileId)){return existing;}var documentRecord=findLessonFileRecord_(lessonId,LESSON_FILE_TYPES.DOCUMENT);if(!documentRecord||!safeText_(documentRecord.driveFileId))throw Error('لا يوجد مستند Google Doc جاهز قبل توليد PDF');var folder=getLessonFolderPath_('02 PDF الدروس');var pdfSource=DriveApp.getFileById(documentRecord.driveFileId);var pdfBlob=pdfSource.getAs('application/pdf');var pdfFile=folder.createFile(pdfBlob.setName((lesson.lessonCode||lessonId)+' - '+(lesson.title||'درس')+'.pdf'));var fileRecord=registerLessonFile_(lessonId,LESSON_FILE_TYPES.PDF,pdfFile.getName(),pdfFile.getId(),folder.getName?folder.getName():('02 PDF الدروس'),documentRecord.templateId||getActiveLessonTemplate_(),documentRecord.templateVersion||getActiveLessonTemplateVersion_(),lesson.version||1,{sourceDocumentId:documentRecord.driveFileId,generatedBy:currentEmail_(),generatedAt:now_()});lesson.pdfFileId=fileRecord.id;lesson.updatedAt=now_();DatabaseService.upsert('LESSONS',lesson);return fileRecord;}

var LessonWorkflowService={ensureLessonSchema:function(){return ensureLessonSchema_();},createLesson:function(data){return createLesson_(data||{});},getLesson:function(lessonId){return getLesson_(lessonId);},saveDraft:function(lessonId,data){return saveLessonDraft_(lessonId,data||{});},submitForReview:function(lessonId,comment){return submitLessonForReview_(lessonId,comment||'');},requestRevision:function(lessonId,comment){return requestRevision_(lessonId,comment||'');},approve:function(lessonId,comment){return approveLesson_(lessonId,comment||'');},publish:function(lessonId,comment){return publishLesson_(lessonId,comment||'');},archive:function(lessonId,comment){return archiveLesson_(lessonId,comment||'');},generateDocument:function(lessonId,templateId){return generateLessonDocument_(lessonId,templateId||null);},generatePdf:function(lessonId){return generateLessonPdf_(lessonId);},statusLabel:function(status){return getLessonStatusLabel_(status);},transitionAllowed:function(fromStatus,toStatus){return lessonTransitionAllowed_(fromStatus,toStatus);}};

var LessonService=LessonWorkflowService;