function ensureEvaluationSchema_(){DatabaseService.ensureSheet('EVALUATION_FORMS',['id','title','description','version','status','createdBy','createdAt','updatedAt']);DatabaseService.ensureSheet('EVALUATION_CRITERIA',['id','formId','formVersion','label','description','responseType','optionsJson','required','sortOrder','status','createdAt','updatedAt']);DatabaseService.ensureSheet('EVALUATIONS',['id','studentId','classId','subjectId','formId','formVersion','teacherEmail','academicYearId','status','startedAt','updatedAt','submittedAt','lockedAt']);DatabaseService.ensureSheet('EVALUATION_RESPONSES',['id','evaluationId','criterionId','value','updatedAt']);}
function evaluationPermission_(p){authorize_(p);}
function evaluationRows_(){ensureEvaluationSchema_();return DatabaseService.rows('EVALUATIONS');}
function assignmentScope_(){var email=currentEmail_();var rows=DatabaseService.rows('USER_ASSIGNMENTS')||[];return {all:UserRoleService.hasRole('ADMIN')||UserRoleService.hasRole('EVALUATION'),classes:rows.filter(function(r){return String(r.userEmail||'').toLowerCase()===email&&/CLASS/i.test(r.entityType||'');}).map(function(r){return String(r.entityId);}),subjects:rows.filter(function(r){return String(r.userEmail||'').toLowerCase()===email&&/SUBJECT/i.test(r.entityType||'');}).map(function(r){return String(r.entityId);})};}
function evaluationInScope_(data,scope){if(scope.all)return true;var student=DatabaseService.find('STUDENTS',data.studentId),classId=String(data.classId||student&&student.classId||'');return scope.classes.indexOf(classId)>=0&&scope.subjects.indexOf(String(data.subjectId||''))>=0;}
function activeForm_(id,version){var f=DatabaseService.find('EVALUATION_FORMS',id);if(!f||String(f.status)!=='ACTIVE'||(version&&String(f.version)!==String(version)))throw Error('نموذج التقييم غير متاح حاليًا');return f;}
function historicalForm_(id,version){var f=DatabaseService.find('EVALUATION_FORMS',id);if(!f||String(f.version)!==String(version))throw Error('نسخة نموذج التقييم غير موجودة');return f;}
function criteriaForForm_(form){return (DatabaseService.rows('EVALUATION_CRITERIA')||[]).filter(function(r){return String(r.formId)===String(form.id)&&String(r.formVersion)===String(form.version)&&String(r.status||'ACTIVE')!=='ARCHIVED';}).sort(function(a,b){return Number(a.sortOrder||0)-Number(b.sortOrder||0);});}
function saveEvaluationForm_(data){evaluationPermission_('MANAGE_EVALUATIONS');ensureEvaluationSchema_();data=data||{};var existing=data.id&&DatabaseService.find('EVALUATION_FORMS',data.id);var used=(DatabaseService.rows('EVALUATIONS')||[]).some(function(e){return existing&&String(e.formId)===String(existing.id)&&String(e.formVersion)===String(existing.version);});if(existing&&used&&Number(data.version||existing.version)<=Number(existing.version)){throw Error('لا يمكن تعديل نسخة نموذج مستخدمة؛ أنشئ إصدارًا جديدًا');}var form={id:String(data.id||uuid_()),title:safeText_(data.title),description:safeText_(data.description),version:Number(data.version||1),status:safeText_(data.status||'DRAFT'),createdBy:existing&&existing.createdBy||currentEmail_(),createdAt:existing&&existing.createdAt||now_(),updatedAt:now_()};if(!form.title)throw Error('عنوان النموذج مطلوب');DatabaseService.upsert('EVALUATION_FORMS',form);(data.criteria||[]).forEach(function(c,i){if(!safeText_(c.label))throw Error('اسم المعيار مطلوب');DatabaseService.upsert('EVALUATION_CRITERIA',{id:String(c.id||uuid_()),formId:form.id,formVersion:form.version,label:safeText_(c.label),description:safeText_(c.description),responseType:safeText_(c.responseType||'TEXT'),optionsJson:json_(c.options||[]),required:c.required!==false,sortOrder:i,status:'ACTIVE',createdAt:c.createdAt||now_(),updatedAt:now_()});});audit_('FORM_SAVE','EVALUATION_FORMS',form.id,existing,form);return {form:form,criteria:criteriaForForm_(form)};}
function activateEvaluationForm_(id){evaluationPermission_('MANAGE_EVALUATIONS');var f=DatabaseService.find('EVALUATION_FORMS',id);if(!f)throw Error('النموذج غير موجود');var rows=DatabaseService.rows('EVALUATION_FORMS');rows.forEach(function(r){if(String(r.id)!==String(id)&&String(r.status)==='ACTIVE'){r.status='ARCHIVED';r.updatedAt=now_();DatabaseService.upsert('EVALUATION_FORMS',r);}});f.status='ACTIVE';f.updatedAt=now_();DatabaseService.upsert('EVALUATION_FORMS',f);audit_('FORM_ACTIVATE','EVALUATION_FORMS',id,null,f);return f;}
function listEvaluationForms_(){evaluationPermission_('VIEW_EVALUATIONS');ensureEvaluationSchema_();return DatabaseService.rows('EVALUATION_FORMS').map(function(f){return {form:f,criteria:criteriaForForm_(f)};});}
function evaluationWrite_(id,payload,submit){evaluationPermission_('MANAGE_EVALUATIONS');var e=id?DatabaseService.find('EVALUATIONS',id):null,before=e&&JSON.parse(json_(e));payload=payload||{};var scope=assignmentScope_();if(e&&!evaluationInScope_(e,scope))throw Error('ليس لديك صلاحية لهذا التقييم');var form=activeForm_(payload.formId||e&&e.formId,payload.formVersion||e&&e.formVersion);var criteria=criteriaForForm_(form),responses=payload.responses||[],responseMap={};responses.forEach(function(r){responseMap[String(r.criterionId)]=safeText_(r.value);});if(submit)criteria.forEach(function(c){if(c.required!==false&&!responseMap[String(c.id)])throw Error('يرجى استكمال المعايير المطلوبة');if(['SELECT','RADIO'].indexOf(String(c.responseType).toUpperCase())>=0&&responseMap[String(c.id)]){var options;try{options=JSON.parse(c.optionsJson||'[]');}catch(x){options=[];}if(options.indexOf(responseMap[String(c.id)])<0)throw Error('قيمة معيار التقييم غير صالحة');}});var data=e||{id:nextId_('evaluation'),studentId:String(payload.studentId||''),classId:String(payload.classId||''),subjectId:String(payload.subjectId||''),formId:form.id,formVersion:form.version,teacherEmail:currentEmail_(),academicYearId:String(payload.academicYearId||''),status:'IN_PROGRESS',startedAt:now_()};if(!data.studentId||!data.classId||!data.subjectId||!evaluationInScope_(data,scope))throw Error('الطالب والصف والمادة يجب أن تكون ضمن نطاق إسنادك');if(data.status==='SUBMITTED'||data.status==='LOCKED')throw Error('لا يمكن تعديل تقييم مرسل');data.status=submit?'SUBMITTED':'IN_PROGRESS';data.updatedAt=now_();if(submit)data.submittedAt=now_;DatabaseService.upsert('EVALUATIONS',data);responses.forEach(function(r){var c=DatabaseService.find('EVALUATION_CRITERIA',r.criterionId);if(!c||String(c.formId)!==String(form.id)||String(c.formVersion)!==String(form.version))throw Error('معيار تقييم غير صالح');DatabaseService.upsert('EVALUATION_RESPONSES',{id:String(r.id||uuid_()),evaluationId:data.id,criterionId:c.id,value:safeText_(r.value),updatedAt:now_()});});audit_(submit?'EVALUATION_SUBMIT':'EVALUATION_SAVE','EVALUATIONS',data.id,before,data);return evaluationById_(data.id);}
function evaluationById_(id){var e=DatabaseService.find('EVALUATIONS',id);if(!e||!evaluationInScope_(e,assignmentScope_()))throw Error('ليس لديك صلاحية لهذا التقييم');var f=historicalForm_(e.formId,e.formVersion);return {evaluation:e,form:f,criteria:criteriaForForm_(f),responses:(DatabaseService.rows('EVALUATION_RESPONSES')||[]).filter(function(r){return String(r.evaluationId)===String(id);})};}
function getTeacherEvaluationData_(){evaluationPermission_('VIEW_EVALUATIONS');var scope=assignmentScope_();var students=DatabaseService.rows('STUDENTS').filter(function(s){return scope.all||scope.classes.indexOf(String(s.classId))>=0;});var forms=DatabaseService.rows('EVALUATION_FORMS').filter(function(f){return String(f.status)==='ACTIVE';});var evaluations=evaluationRows_().filter(function(e){return evaluationInScope_(e,scope);});return {students:students,forms:forms,evaluations:evaluations};}
function evaluationHistory_(){return getTeacherEvaluationData_().evaluations.map(function(e){return evaluationById_(e.id);});}
function evaluationDashboard_(){var rows=getTeacherEvaluationData_().evaluations;return {total:rows.length,submitted:rows.filter(function(e){return e.status==='SUBMITTED'||e.status==='LOCKED';}).length,inProgress:rows.filter(function(e){return e.status==='IN_PROGRESS';}).length};}
var EvaluationService={saveForm:saveEvaluationForm_,activateForm:activateEvaluationForm_,listForms:listEvaluationForms_,save:function(id,p){return evaluationWrite_(id,p,false);},submit:function(id,p){return evaluationWrite_(id,p,true);},get:function(id){return evaluationById_(id);},teacherData:getTeacherEvaluationData_,history:evaluationHistory_,dashboard:evaluationDashboard_};
